### ISSUE TITLE
Phishing Grading Algorithm

### ISSUE THREAD

**Issue by pranmar123** [pranmar123/AntiPhish#13]
- Create a python script that will take in input text (the body of a message), but if there is not any text in the body of the email, then extract the link of the picture (send that over to the Google API)
- Take in the sender's email address as an input and see if we can do anything with that
- Figure out common phishing email patterns (grammar mistakes, the sender's email, etc.)
- Come up with the algorithm
- Document the rules used and the weights for each of the rules

**Comment by AlecHolloway** [comment]
A link to a project doing the exact same thing. The algorithm to detect phishing is in JavaScript however.
https://github.com/brandonnix95/EmailPhishing

**Comment by AlecHolloway** [comment]
Common Phishing Email Patterns:
•	A Sense of Urgency
•	Impersonal (generic greeting)
•	Scare tactics
•	Run on sentences
•	Malicious Link ( a link that looks legit but when hovered over is sketchy )

https://www.varonis.com/blog/spot-phishing-scam/

**Comment by pranmar123** [comment]
@Abdulyafai Once you get your computer running again can you look at the article that Alec provided (https://www.varonis.com/blog/spot-phishing-scam/) and create 7-10 rules and provide a weight for each of them so we can have the base for the algorithm.

**Comment by Abdulyafai** [comment]
I see that almost all phishing emails have links or attachments to them that contain malware or harmful links. So I'll start implementing the API for checking harmful links, and then it'll be easy to decide how to weight rules for phishing emails.

**Comment by AlecHolloway** [comment]
I am currently working on checking for typos, run-on sentences, and a sense of urgency. I do not think these will have much weight to them however because these are common mistakes.
