### ISSUE TITLE
Error with including requirements on the script

### ISSUE THREAD

**Issue by pranmar123** [pranmar123/AntiPhish#24]
- @Abdulyafai Can you provide a screenshot of the error?

**Comment by Abdulyafai** [comment]
<img width="957" alt="2021-03-19_18-18-17" src="https://user-images.githubusercontent.com/46353570/111851148-3816c400-88e0-11eb-832c-6ba0fbd86aee.png">

This is a screen shot of the error. I pushed the extension code with the API code added to it in a [errorCode ](https://github.com/pranmar123/AntiPhish/blob/errorCode/dist/extension.js) branch.

**Comment by Abdulyafai** [comment]
Axios is a requirement that needs to be added for the JS to send HTTP requests. it could be downloaded using the command `npm install axios`

**Comment by Abdulyafai** [comment]
The problem for this issue is that `require()` doesn't exist in the browser/client-side JavaScript. Fixing this can be down using a CommonJS (Browserify) implementation. It has synchronous dependencies like Node.js.
