### ISSUE TITLE
Integrate gmail.js api to our boilerplate code

### ISSUE THREAD

**Issue by pranmar123** [pranmar123/AntiPhish#3]
Integrate gmail.js api to our boilerplate code

Use these repos for reference:
https://github.com/KartikTalwar/gmail.js/
https://github.com/josteink/gmailjs-node-boilerplate

**Comment by pranmar123** [comment]
After further investigation, I think we can approach this issue in two ways:

1. We use the extension to read the email page's HTML and extract the body of the email text on the HTML source code 
OR
2. We use this gmail.js. Using this may cause extra work, but it could pay off in the long run.

We will discuss this in a future meeting.

**Comment by d-air1** [comment]
gmail.js has been integrated into our codebase. It sits in the javascript folder along with its dependency jquery.
