### ISSUE TITLE
Additional investigation on boilerplate code

### ISSUE THREAD

**Issue by pranmar123** [pranmar123/AntiPhish#5]
After testing the boilerplate code that we initially wanted to go with, I found that it was too complicated and there was not enough documentation to understand on it. I have identified two potential boilerplate that we can use OR we can go over the original boilerplate code that was chosen last semester and try to figure out how the layout works.

1. Original boilerplate code that we selected last semester: https://github.com/EmailThis/extension-boilerplate
2. The boilerplate codes that I identified and tested: 
https://extensionizr.com/!#{%22modules%22:[%22hidden-mode%22,%22with-bg%22,%22with-persistent-bg%22,%22no-options%22,%22no-override%22],%22boolean_perms%22:[],%22match_ptrns%22:[]}
https://github.com/duo-labs/chrome-extension-boilerplate

**Comment by d-air1** [comment]
I think the first one is the best. I'll try and get a working sample and see what I can do with it.

**Comment by d-air1** [comment]
I'm just closing this since we have gone with the first result and integrated it already.
