### ISSUE TITLE
Investigate external APIs

### ISSUE THREAD

**Issue by pranmar123** [pranmar123/AntiPhish#7]
* Explore the possibility of using an external API instead of creating our own script for determining phishing links
* We should be able to send URLS to this API and it tells us if its a scam or not
* Dashon suggested using: Google Safe Browsing API

**Comment by Abdulyafai** [comment]
Looking to Google Safe Browsing API, it looks like it is the perfect API for AntipPhish. It works by sending a post request to the API with the URL need to be tested. The API will respond send back the result of the test (harmful URL or not).
