### ISSUE TITLE
Investigate image-based phishing emails

### ISSUE THREAD

**Issue by pranmar123** [pranmar123/AntiPhish#8]
* Look into and find out how many phishing emails contain images
* Find out whether the emails that contain images are links (when you click the image it directs you to a site) or if they are just images that have phishing text on them
* Think of any methods of how we can analyze the text from the images

**Comment by AlecHolloway** [comment]
[image_spam.docx](https://github.com/pranmar123/AntiPhish/files/5881830/image_spam.docx)
